apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-test
  region: ap-south-1
addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccount: aws-node
