apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-test
  region: ap-south-1
  version: "1.30"
availabilityZones:
  - ap-south-1a
  - ap-south-1b
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
privateCluster:
  enabled: false
  skipEndpointCreation: false
cloudWatch:
  clusterLogging: {}
iam:
  # vpcResourceControllerPolicy: true
  # withOIDC: true
addonsConfig: {}
accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
